# Generated by Django 3.2 on 2021-12-08 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='item',
            name='prod',
        ),
        migrations.DeleteModel(
            name='cartlist',
        ),
        migrations.DeleteModel(
            name='item',
        ),
    ]
